server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ${APP_NAME:bank-app}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:true}
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  cache:
    type: redis

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: TRACE

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
  show-actuator: true

redis:
  url: ${REDIS_URL:redis://localhost:6379}
  password: ${REDIS_PASSWORD:redis_pwd}
  timeout: ${REDIS_TIMEOUT:5000}

---
spring:
  config:
    activate:
      on-profile: development
  jpa:
    show-sql: true
logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    com.bankapp: DEBUG

---
spring:
  config:
    activate:
      on-profile: production
  jpa:
    show-sql: false
logging:
  level:
    root: INFO
    org.springframework: WARN
    com.bankapp: INFO